basePath: /
host: localhost:8000
info:
  contact:
    email: moraes@mail.com
    name: Moraes
    url: github.com/antoniomjr
  description: Product API with authentication
  license:
    name: MIT
    url: http://mit.com
  termsOfService: http://swagger.io/terms/
  title: Go Experts API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
